[programs.localnet]
anchor_test = "C6wNMRuGEpxhmVqg4gpk6rqxhYZyE66sQWW3d8BWNbMa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 100000000 tests/anchor-test.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000000 tests/50-user-repeated.ts"